<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LINBLRB6VJGB3" failures="1" tests="1" name="Default test(failed)" time="0.055" errors="0" timestamp="2022-11-22T19:54:29 IST">
  <testcase classname="com.test.cricket.PlayersSelection" name="verifyForeignPlayers" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [4] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [4] but found [11]
at com.test.cricket.PlayersSelection.verifyForeignPlayers(PlayersSelection.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyForeignPlayers -->
</testsuite> <!-- Default test(failed) -->
